name: technical_test_consware
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  intl: ^0.18.1
  page_transition: ^2.0.9
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
      - asset: assets/fonts/poppins/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/poppins/Poppins-Bold.ttf
        weight: 700
  - family: Product-sans
    fonts:
      - asset: assets/fonts/product-sans/Product Sans Regular.ttf
      - asset: assets/fonts/product-sans/Product Sans Italic.ttf
        style: italic
      - asset: assets/fonts/product-sans/Product Sans Bold.ttf
        weight: 700